### ISSUE TITLE
How to install on Debian Jessie

### ISSUE THREAD

**Issue by HagenMo** [Palakis/obs-websocket#42]
At first: Many thanks for the project!

Unfortunately, I can't get it to work on Debian Jessie. I installed the newest version of OBS, then installed obs-websocket with the commands provided in your readme.md but the socket is not listed in the tools of OBS.

Is there a more detailed installation guide or has someone an idea / guess of what could be wrong?

Many thanks!

**Comment by Palakis** [comment]
Hi @HagenMo, does the plugin builds without errors ?

**Comment by HagenMo** [comment]
There is one error occuring when I cmake the DLIBOBS_INCLUDE_DIR showing he cant find data or directory:

Can't open perl script "/usr/lib/obs-websocket/scripts/config.pl"

And indeed, the whole "scripts" folder is missing.

**Comment by Palakis** [comment]
Can you list the contents of `/usr/lib/obs-plugins/`?

**Comment by HagenMo** [comment]
Sure:

-rw-r--r--   1 root root 587384 Feb 23 16:36 frontend-tools.so
-rw-r--r--   1 root root  79264 Feb 23 16:36 image-source.so
-rw-r--r--   1 root root  54352 Feb 23 16:36 linux-alsa.so
-rw-r--r--   1 root root 409608 Feb 23 16:36 linux-capture.so
-rw-r--r--   1 root root 608696 Feb 23 16:36 linux-decklink.so
-rw-r--r--   1 root root  37712 Feb 23 16:36 linux-jack.so
-rw-r--r--   1 root root  70240 Feb 23 16:36 linux-pulseaudio.so
-rw-r--r--   1 root root 102232 Feb 23 16:36 linux-v4l2.so
-rw-r--r--   1 root root 538288 Feb 23 16:36 obs-ffmpeg.so
-rw-r--r--   1 root root 259128 Feb 23 16:36 obs-filters.so
-rw-r--r--   1 root root 442736 Feb 23 16:36 obs-outputs.so
-rw-r--r--   1 root root 102952 Feb 23 16:36 obs-transitions.so
-rw-r--r--   1 root root  91256 Feb 23 16:36 obs-x264.so
-rw-r--r--   1 root root 252432 Feb 23 16:36 rtmp-services.so
-rw-r--r--   1 root root 103520 Feb 23 16:36 text-freetype2.so
-rw-r--r--   1 root root  94448 Feb 23 16:36 vlc-video.so

**Comment by Palakis** [comment]
`obs-websocket.so` should be there but it obviously isn't. Make sure `CMAKE_INSTALL_PREFIX` is set to `/usr`, and if it is, make sure you ran `sudo make install`.

**Comment by HagenMo** [comment]
Ok, thats what happens, when I run `make install`

/usr/lib/obs-websocket/obs-websocket.cpp: In function ‘bool obs_module_load()’:
/usr/lib/obs-websocket/obs-websocket.cpp:51:7: error: ‘menu_cb’ does not name a type
  auto menu_cb = [] {
       ^
/usr/lib/obs-websocket/obs-websocket.cpp:54:57: error: ‘menu_cb’ was not declared in this scope
  menu_action->connect(menu_action, &QAction::triggered, menu_cb);
                                                         ^
CMakeFiles/obs-websocket.dir/build.make:62: recipe for target 'CMakeFiles/obs-websocket.dir/obs-websocket.cpp.o' failed
make[2]: *** [CMakeFiles/obs-websocket.dir/obs-websocket.cpp.o] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/obs-websocket.dir/all' failed
make[1]: *** [CMakeFiles/obs-websocket.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Palakis** [comment]
Hmm, gonna investigate this. Can you give your GCC and G++ version numbers please?

**Comment by HagenMo** [comment]
They are both at 4.9.2

Thank you for your effort!

**Comment by Palakis** [comment]
Can confirm it works on Ubuntu 16.10 with GCC 6.2.0. Gonna setup a Debian Jessie VM and test compiling on it as well.

**Comment by HagenMo** [comment]
Hi,
may I cautiously ask if you already investigated something?

**Comment by Palakis** [comment]
Hi,
No I didn't, I had other things to do these days, related and unrelated to obs-websocket so I didn't took time to check this, even though I didn't forget this issue. I cleared today the issue and feature backlog for the next release so I'll have more time for testing during the coming days.

**Comment by Palakis** [comment]
@HagenMo can you please sync your local copy with the repo's `master` and try to build it, please?

**Comment by Palakis** [comment]
No updates from @HagenMo on this, so : closing.
