### ISSUE TITLE
Unable to compile on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by asquelt** [Palakis/obs-websocket#59]
this distro is equipped with Qt 5.2.1 and is still supported until April 2019.
obs-studio provides ~~build instructions~~ PPA repository and packages for trusty with ffmpeg-next enabled.

obs-websocket compile breaks on:
```
/home/travis/build/asquelt/obs-websocket/WSEvents.cpp:81:3: error: no matching function for call to ‘QTimer::singleShot(int, WSEvents::WSEvents(WSServer*)::__lambda0)’
  });
   ^
/home/travis/build/asquelt/obs-websocket/WSEvents.cpp:81:3: note: candidates are:
In file included from /usr/include/qt5/QtCore/QTimer:1:0,
                 from /home/travis/build/asquelt/obs-websocket/WSEvents.cpp:21:
/usr/include/qt5/QtCore/qtimer.h:81:17: note: static void QTimer::singleShot(int, const QObject*, const char*)
     static void singleShot(int msec, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:81:17: note:   candidate expects 3 arguments, 2 provided
/usr/include/qt5/QtCore/qtimer.h:82:17: note: static void QTimer::singleShot(int, Qt::TimerType, const QObject*, const char*)
     static void singleShot(int msec, Qt::TimerType timerType, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:82:17: note:   candidate expects 4 arguments, 2 provided
```

whole build log: https://travis-ci.org/asquelt/obs-websocket/jobs/219241067

**Comment by Palakis** [comment]
I modified this call to use a slot instead of a lambda function. Can you try it, please?

**Comment by asquelt** [comment]
yes, that fixed the build.

https://travis-ci.org/asquelt/obs-websocket/jobs/222070782

**Comment by Palakis** [comment]
\o/

**Comment by Palakis** [comment]
So making Linux builds on Travis works. Once we figure out the problem with OS X builds, you'll be able to submit a PR for Linux and OS X builds on Travis.
